### PR TITLE
CB-12667 android: Added logic for searching sensors from Samsung vendor

### PR DESCRIPTION
**Pull request by matrosov-nikita**
### Platforms affected
Android

### What does this PR do?
This PR adds opportunity for searching orientation sensors which have specific orientation type (it's relevant for Samsung devices).

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-device-orientation/pull/34/commits/f055c16400b823923265d993c1ec35d9cfe43bf0)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-device-orientation-pr/23/)

 66 tests run, 9 skipped, 0 failed.

**Comment by infil00p** [comment]
@matrosov-nikita Which Samsung devices are affected? All of them? Only the Samsung Galaxy S3/4/5? If we could get more info on that, we can test for this and try and make there there's no regressions.

**Comment by matrosov-nikita** [comment]
@infil00p, sorry for late reply, I've tested a plugin with two Samsung devices:
1) Samsung Galaxy Core Prime VE Duos SM-G361H (Android 5.1)
samsung galaxy core prime ve duos sm-g361h
It has only 'Screen Orientation Sensor' with orientation type 65558
2) Samsung Galaxy S5 (Android 5.1)
samsung
It has two orientation sensors - 'Screen Orientation Sensor'(type=65558) and 'Orientation Sensor'(type=3)

For Samsung Galaxy S5 plugin works perfect. So, not all devices are affected. It depends on what orientation sensors the device has.

**Comment by filmaj** [comment]
A quick Google search reveals that the Note 2 and Note 4 also have this sensor type:

http://www.mattcurry.com/projects-2/the-n-a-o-m-i-project/note4-sensor-output/
https://github.com/hbibel/TapToUnlock/wiki/Sensor-Dumps-of-Different-Devices

Interestingly, the only device I was able to dig up that his the Samsung-specific orientation sensor _but not the "normal" orientation sensor_ is the SM-G361H model @matrosov-nikita points out.

@matrosov-nikita are you able to confirm that this device's Samsung Orientation Sensor works and provides the same kind of data as the regular android Orientation sensor?

**Comment by matrosov-nikita** [comment]
@filmaj, I can confirm that auto and manual tests work w/ my fix.

**Comment by petrot** [comment]
This commit will fix the compass problem on samsung devices? e.g. Samsung Galaxy J5 (2016)

**Comment by matrosov-nikita** [comment]
@petrot, what do you mean 'compass problem`. Do you have any particular cases which don't work for you? I could test them with this fix.

**Comment by petrot** [comment]
One of my user has a Galaxy J5, but as I recognized yesterday, this phone does not have a sensor. So my problem has been solved.. :)

**Comment by matrosov-nikita** [comment]
@filmaj, @infil00p, do I need to do something else on this issue?

**Comment by filmaj** [comment]
@matrosov-nikita as long as you tested this on one of the real devices affected by the issue, and confirmed the fix, I am good to have this merged.

**Comment by filmaj** [comment]
Just realized you don't have committer rights - I will merge this in.

**Comment by filmaj** [comment]
@matrosov-nikita can you rebase with latest master first, please?

**Comment by matrosov-nikita** [comment]
@filmaj, done

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-device-orientation/pull/34/commits/a77b4fa0a410d22a0d36edddb0cc0a603d8dea43)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-device-orientation-pr/25/)

 66 tests run, 9 skipped, 0 failed.

**Pull request merged**
